# About this toolkit

Recent decades have seen a proliferation of new pedagogical approaches in humanities teaching. This comes in the wake of a growing awareness that students learn in a variety of ways, and that a more multifocal context provides more robust learning outcomes. This opening in pedagogical technique has come at the same time as an increased desire across a range of HEIs to embed student learning in practical careers contexts. Especially in the humanities, where popular stereotypes of the bookish and impractical scholar abound, it is important to help students (and the wider public) to appreciate the way that the cultivation of critical reading of both texts and culture, eloquent writing, and analytical skills can enable success across a variety of career pathways - not simply in academia.

While there is a significant literature detailing implementation of these new approaches in disciplines such as science, education and business, there are far fewer documented examples in the context of humanities teaching. The publication of this open toolkit is meant to address some of this gap, by providing a complete range of materials with some accompanying commentary that were developed in the context of a second year undergraduate course at the University of Birmingham, "Religion in the Public Sphere". We provide some specific details of our own delivery, including some challenges and successes. 

In the course students partner in small groups with a real local employer. The employer has set a problem that they are facing in their work, and students work to analyse the context and design a project which can address the "problem". While the course detailed below is inflected towards the study of religion, it has been designed in such a way that it might be easily adapted to a range of other humanities disciplines. We hope that others who use this toolkit may share feedback and changes they've made which might benefit the wider community of pedagogues integrating careers training and consultancy into humanities teaching.

If you are interested in reading more about Work Integrated Learning, you may want to consult some of the following:

- A Practical Guide for Work Integrated Learning
- Pedagogy for employability
- Impact of WIL on statement on work readiness
- Employability and entrepreneurship embedded in professional placements
- Connecting enterprise and graduate employability Challenges to the higher education culture and curriculum
- WIL Guide June 2014
