# Step 2: Course (re)design and Delivery

## Consultancy projects - pedagogical design challenges

There were two primary design challenges facing our course. First, we brought a desire to integrate more practical content (i.e. engagement with employers, fieldwork, skills training, etc.) without detracting from student learning on more abstract critical theory which is also a chief aim of the course. As you will see below, we have attempted to interweave practical with abstract and included several exercises which are meant to synthesise student learning with regards to critical theory in the study of religion with the very concrete context of their consultancy project and the employer they are matched with. 

Second, because of the "real world" context, there is a higher level of risk that student learning may stall when faced with unexpected challenges etc., so proactive outreach to students is key. Though on this course, there was ongoing input from professional services staff and lectures from other academic staff, logistics were managed by just one person, so there was a need to ensure that course management was efficient and that student feedback was carefully solicited and reflection facilitated at key milestones. These two tasks of interweaving theory and practice; and streamlining course management surface in a variety of ways in the below toolkit.


## What did we learn? Reviewing year 1

As you will read in the next chapter, we undertook an extensive review of the course which engaged with students and organisational partners. The toolkit involves some resources which you can use to replicate the review process for your own course, but it is worth mentioning some of what we learned from our first year of the course which will illuminate some of the design elements below.

- The interviews with industry informed us that structure is needed to guide both hosts and students through the experience. To help all parties have an understanding of their role (and each other's roles) we designed a 'roles and responsibilities' document (mentioned below). We also asked employers to indicate specifically how often they would prefer to be in contact with student teams (this varied widely). 
- Students struggled to maintain progress with only the project completion as a milestone for their work. To keep students on track, we added a series of more granular milestones and students will be asked at the beginning of the project to complete a project plan and present it to the organisation host during their first meeting after the initial orientation. This project plan can be used the structure the rest of the meetings that the host has with the students and to ensure that expectations are aligned.
- In speaking to students about their experience, we learned that they sometimes felt adrift in this very new context. We added a check-in during the lecture time. Students will be asked to present brief updates to the rest of the group, similar to updates given in a professional team meeting/ boardroom. This enables a low risk context for student teams to raise concerns, adjust expectations and troubleshoot problems as they arise.
- We also discovered that students and organisations all had different conceptions of what "consultancy" work implied. Along with the written materials developed for employers, we invited an external speaker (who is themselves a professional consultant) to give a talk to students on 'what is a consultant?' - explaining how their role is different from the usual 'employee'.
- Past students will be asked if they would like to peer support the new teams of students during their project. 
- We have added further reflection sessions that encourage students to reflect on the skills they have gained during the module.



## About our course

This course, a core offering on our "Politics, Religion, and Philosophy" degree programme provides students with a set of critical tools for interpreting and critiquing the different ways that religion can be configured across different public contexts. The course covers 200 total hours of student work across two semesters. This includes:

- Ten 2-hour lectures (many of these include problem-based learning exercises)
- Five 2-hour research skills training sessions (we provide initial introductions to survey design, focus groups, ethnography, and GIS, with the expectation that each student will "specialise" in just one of these forms of research)
- 20-25 hours of engagement with their exployer / context
- 7 hours engaging in critical self-reflections
- 5 hours of preparation for project presentations
- 70 hours of individual study
- 15 hours of fieldwork
- 45 hours of work on the policy project


## Course structure

The course aims to integrate a range of different modes of teaching and learning:

1. Lectures on critical theory & religious studies
2. Training in empirical research methods and fieldwork
3. Practical professional skills training sessions 
4. Student presentations and workshops
5. Critical self-reflection

We expect that (1) will be altered to suit another course in some similar configuration of texts, theory, and context. 


### Research Methods and Fieldwork

Embedding training in research methods (2) is especially critical for this course design, given that many students in the humanities will not necessarily have gotten training in their first year. We are developing a combination of lab-books (for flipped-classroom style instruction), and open-source workshops which will be put up and will be available for use in a later version of this toolkit. 

We have also designed (see further below) a series of worksheets to structure and facilitate some of the early stages of research design and reflection. These are all included as part of this toolkit which you can modify as necessary.


### Skills training

For this course, we have opted to work with very brief (15-30 minute presentations) to highlight the professional skills that are being drawn upon and learned along the course. In the present configuration, aside from research methods training there are five core skills being higlighted:

- Self-presentation (i.e. writing a C.V.)
- Critical self-reflection
- The nature of consultancy work (as opposed to ordinary employment)
- Board-room presentations (i.e. of work in progress)
- Working with peer review

These skills training sessions dovetail with self-reflective prompts (formative assessment) and are synthesised in the final (summative) policy project write-up.


## Timeline

[embedded image here]


## Some practical advice:

Students will find the course very challenging.